trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: BUILD
  jobs:
  - template: adf-build-job.yml
    parameters:
      subscriptionId: 70d3ca1d-a411-4231-8ec2-eae8259a6010
      resourceGroupName: AzureCourse
      dataFactoryName: azurecourseadf213123
      repoRootFolder: /data-factory/
      packageJsonFolder: /devops/